name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tlienart/xranklin-build-action@latest
        with:
          BASE_URL_PREVIX: "coder-xranklin-demo"
